on:
  push:
    tags:
        - v*
        
name: Release Build

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v3
        with:
          name: tcr-${{ matrix.os }}
          path: |
            target/release/tcr
            target/release/tcr.exe
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      # We don't need the repo, grab all artifacts from the build stage
      # The plugin puts each artifact in a folder of `artifactname`
      - uses: actions/download-artifact@v2

      - name: Display fetched artifacts
        run: ls -R
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "TCR ${{github.ref_name}}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            tcr-windows-latest/*.zip
            tcr-ubuntu-latest/*.zip
