on:
  push:
    tags:
        - v*
        
name: Release Build

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v3
        with:
          name: tcr-${{ matrix.os }}
          path: target/release/tcr[.exe]
